//! Write a palette into everything that displays it.
//!
//! Every "this UI element uses that M3 role" decision lives in the tables
//! below; the PowerShell profile, the statusline and the cmd prompt only
//! render the values generated from them.
//!
//! Each writer only touches its file when the content actually changes, so
//! the terminals don't reload (and flash) on a no-op re-check.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value, json};

use crate::palette::{CUSTOM, Colors, Palette, rgb};

type Result<T> = std::result::Result<T, String>;

const fn scheme_name(dark: bool) -> &'static str {
    if dark { "Material You Dark" } else { "Material You Light" }
}

// --- Role tables -----------------------------------------------------------

// Pills sit directly on the terminal background. Neighbouring statusline
// segments alternate primary/secondary/tertiary families so they always
// differ, whatever the wallpaper. Warn/danger replace the whole segment.
pub const PILLS: [(&str, &str, &str); 9] = [
    ("DIR", "primaryContainer", "onPrimaryContainer"),
    ("BRANCH", "secondaryFixedDim", "onSecondaryFixed"),
    ("MODEL", "tertiaryContainer", "onTertiaryContainer"),
    ("COST", "secondaryFixed", "onSecondaryFixed"),
    ("CTX", "primaryFixedDim", "onPrimaryFixed"),
    ("5H", "tertiaryFixedDim", "onTertiaryFixed"),
    ("7D", "secondaryFixedDim", "onSecondaryFixed"),
    ("WARN", "yellowFixed", "onYellowFixed"),
    ("DANGER", "error", "onError"),
];
const TRACK_INK: f64 = 0.30; // progress-bar track = 30% pill ink over the pill

const PROMPT_OK: &str = "primary";
const PROMPT_ERR: &str = "error";

const SYNTAX: [(&str, &str); 13] = [
    // PSReadLine token -> foreground role
    ("Default", "onSurface"),
    ("Command", "primary"),
    ("Parameter", "tertiary"),
    ("Operator", "onSurfaceVariant"),
    ("Variable", "secondary"),
    ("String", "green"),
    ("Number", "yellow"),
    ("Type", "cyan"),
    ("Member", "blue"),
    ("Keyword", "magenta"),
    ("Comment", "outline"),
    ("Error", "error"),
    ("ContinuationPrompt", "outline"),
];
const SELECTION: (&str, &str) = ("secondaryContainer", "onSecondaryContainer");

/// Where the writers write. `Targets::system()` is the real machine; tests
/// point everything at a scratch directory.
pub struct Targets {
    pub out_dir: PathBuf,
    pub terminal_settings: Vec<(&'static str, PathBuf)>,
    /// None: set HKCU\Environment PROMPT. Some(file): write the text there.
    pub prompt_file: Option<PathBuf>,
}

impl Targets {
    pub fn system() -> Self {
        let local = PathBuf::from(std::env::var_os("LOCALAPPDATA").unwrap_or_default());
        let settings = |name: &'static str| {
            (name, local.join("Packages").join(format!("Microsoft.{name}_8wekyb3d8bbwe")).join(r"LocalState\settings.json"))
        };
        Self {
            out_dir: home().join(".config").join("m3-theme"),
            terminal_settings: vec![settings("WindowsTerminal"), settings("IntelligentTerminal")],
            prompt_file: None,
        }
    }

    pub fn cache_path(&self) -> PathBuf {
        self.out_dir.join("palette.json")
    }

    /// Write every target; return the names of the ones that changed.
    pub fn apply(&self, pal: &Palette, dark: bool) -> Vec<String> {
        let mut changed = Vec::new();
        if let Err(e) = std::fs::create_dir_all(&self.out_dir) {
            return vec![format!("FAILED {}: {e}", self.out_dir.display())];
        }
        let c = pal.mode(dark);
        let header =
            format!("# Generated by m3-terminal-theme from {} ({}) - do not edit.", pal.source, if dark { "dark" } else { "light" });
        let mut record = |name: &str, result: Result<bool>| match result {
            Ok(true) => changed.push(name.to_string()),
            Ok(false) => {}
            Err(e) => changed.push(format!("FAILED {name}: {e}")),
        };
        for (name, path) in &self.terminal_settings {
            record(name, terminal_settings(pal, dark, path));
        }
        record("statusline", self.statusline(c, &header));
        record("powershell", self.powershell(c, &header));
        record("cmd_prompt", self.cmd_prompt(c));
        changed
    }

    // --- Claude Code statusline --------------------------------------------

    /// statusline.json for the Rust statusline, statusline.sh for the bash one.
    fn statusline(&self, c: &Colors, header: &str) -> Result<bool> {
        let mut pills = Map::new();
        let mut lines = vec![header.to_string()];
        for (seg, bg, fg) in PILLS {
            let (bg_rgb, fg_rgb) = (ansi_rgb(&c[bg]), ansi_rgb(&c[fg]));
            let track = ansi_rgb(&mix(&c[fg], &c[bg], TRACK_INK));
            lines.push(format!(r#"C_{seg}="{bg_rgb}"; F_{seg}="{fg_rgb}"; T_{seg}="{track}""#));
            pills.insert(seg.into(), json!({"bg": bg_rgb, "fg": fg_rgb, "track": track}));
        }
        let sep = ansi_rgb(&c["outline"]);
        lines.push(format!(r#"C_SEP="{sep}""#));
        let as_json = to_json(&json!({"pills": pills, "sep": sep}), 2) + "\n";
        let changed_json = write_if_changed(&self.out_dir.join("statusline.json"), &as_json)?;
        let changed_sh = write_if_changed(&self.out_dir.join("statusline.sh"), &(lines.join("\n") + "\n"))?;
        Ok(changed_json || changed_sh)
    }

    // --- PowerShell (ASCII: Windows PowerShell 5.1 reads BOM-less files as ANSI)

    fn powershell(&self, c: &Colors, header: &str) -> Result<bool> {
        let fg = |role: &str| format!("$e[38;2;{}m", ansi_rgb(&c[role]));
        let pill = |name: &str| {
            let (_, bg, fg) = pill_roles(name);
            format!("$e[48;2;{}m$e[38;2;{}m", ansi_rgb(&c[bg]), ansi_rgb(&c[fg]))
        };
        let edge = |name: &str| fg(pill_roles(name).1);
        let prompt = BTreeMap::from([
            ("DirPill", pill("DIR")),
            ("DirEdge", edge("DIR")),
            ("BranchPill", pill("BRANCH")),
            ("BranchEdge", edge("BRANCH")),
            ("DirToBranch", edge("DIR") + &format!("$e[48;2;{}m", ansi_rgb(&c[pill_roles("BRANCH").1]))),
            ("Ok", fg(PROMPT_OK)),
            ("Err", fg(PROMPT_ERR)),
        ]);
        let mut syntax: BTreeMap<&str, String> = SYNTAX.iter().map(|&(token, role)| (token, fg(role))).collect();
        syntax.insert("Emphasis", "$e[1m".to_string() + &fg("primary"));
        syntax.insert("Selection", format!("$e[48;2;{}m$e[38;2;{}m", ansi_rgb(&c[SELECTION.0]), ansi_rgb(&c[SELECTION.1])));
        let table = |d: &BTreeMap<&str, String>| {
            d.iter().map(|(k, v)| format!(r#"    {k:<18} = "{v}""#)).collect::<Vec<_>>().join("\n")
        };
        let text = format!(
            "{header}\n$e = [char]27\n$global:M3 = @{{\n{}\n}}\n$global:M3Syntax = @{{\n{}\n}}\n",
            table(&prompt),
            table(&syntax)
        );
        write_if_changed(&self.out_dir.join("palette.ps1"), &text)
    }

    // --- cmd ---------------------------------------------------------------

    /// Set HKCU\Environment PROMPT; broadcast so new terminals/tabs inherit it.
    fn cmd_prompt(&self, c: &Colors) -> Result<bool> {
        let text = cmd_prompt_text(c);
        if let Some(file) = &self.prompt_file {
            return write_if_changed(file, &text);
        }
        if crate::win::get_env_prompt().as_deref() == Some(text.as_str()) {
            return Ok(false);
        }
        crate::win::set_env_prompt(&text)?;
        crate::win::broadcast_environment_change();
        Ok(true)
    }
}

fn pill_roles(name: &str) -> (&'static str, &'static str, &'static str) {
    *PILLS.iter().find(|p| p.0 == name).expect("known pill")
}

/// Rounded DIR pill with the path, then the OK chevron.
///
/// cmd has no hooks to re-read a palette, but PROMPT expands $E to ESC, so
/// the colours are baked in and the variable is rewritten on every change.
fn cmd_prompt_text(c: &Colors) -> String {
    let (_, bg, fg) = pill_roles("DIR");
    let (bg, fg, ok) = (ansi_rgb(&c[bg]), ansi_rgb(&c[fg]), ansi_rgb(&c[PROMPT_OK]));
    format!("$E[0m$E[38;2;{bg}m\u{E0B6}$E[48;2;{bg}m$E[38;2;{fg}m$E[1m $P $E[0m$E[38;2;{bg}m\u{E0B4}$E[0m $E[38;2;{ok}m$E[1m❯$E[0m ")
}

// --- Windows Terminal / Intelligent Terminal -------------------------------

fn wt_scheme(c: &Colors, dark: bool) -> Value {
    // WT calls ANSI magenta "purple"
    let wt = |name: &str| if name == "magenta" { "purple".to_string() } else { name.to_string() };
    let mut m = Map::new();
    let mut put = |k: String, v: &str| {
        m.insert(k, Value::String(v.to_string()));
    };
    put("name".into(), scheme_name(dark));
    put("background".into(), &c["surface"]);
    put("foreground".into(), &c["onSurface"]);
    put("cursorColor".into(), &c["primary"]);
    put("selectionBackground".into(), &c[SELECTION.0]);
    // ANSI black/white are "darkest/lightest", so they swap with the mode.
    put("black".into(), if dark { &c["surfaceContainerHighest"] } else { &c["onSurface"] });
    put("brightBlack".into(), &c["outline"]);
    put("white".into(), if dark { &c["onSurfaceVariant"] } else { &c["surfaceContainerHighest"] });
    put("brightWhite".into(), if dark { &c["onSurface"] } else { &c["surfaceContainerLowest"] });
    for (n, _, _) in CUSTOM {
        put(wt(n), &c[n]);
    }
    for (n, _, _) in CUSTOM {
        put(format!("bright{}", capitalize(&wt(n))), &c[&format!("{n}Bright")]);
    }
    Value::Object(m)
}

fn wt_theme(c: &Colors, dark: bool) -> Value {
    json!({
        "name": scheme_name(dark),
        "window": {
            "applicationTheme": if dark { "dark" } else { "light" },
            "frame": if dark { &c["primaryFixedDim"] } else { &c["primary"] },
            "unfocusedFrame": c["surfaceContainerHighest"],
        },
        "tabRow": {
            "background": c["surfaceContainer"],
            "unfocusedBackground": c["surfaceContainerLow"],
        },
        "tab": {
            "background": "terminalBackground",
            "unfocusedBackground": c["surfaceContainerHigh"],
            "showCloseButton": "hover",
        },
    })
}

/// Add/refresh both schemes + themes; point defaults at them.
fn terminal_settings(pal: &Palette, dark: bool, path: &Path) -> Result<bool> {
    if !path.exists() {
        return Ok(false);
    }
    let text = read_text(path).map_err(|e| e.to_string())?;
    let mut settings: Value = serde_json::from_str(&text).map_err(|e| e.to_string())?;
    let root = settings.as_object_mut().ok_or("settings.json is not an object")?;
    for mode_dark in [true, false] {
        let c = pal.mode(mode_dark);
        upsert(array_entry(root, "schemes")?, wt_scheme(c, mode_dark));
        upsert(array_entry(root, "themes")?, wt_theme(c, mode_dark));
    }
    let profiles = object_entry(root, "profiles")?;
    let defaults = object_entry(profiles, "defaults")?;
    // The scheme follows light/dark by itself; the theme key can't, so it is
    // rewritten when the app mode flips.
    defaults.insert("colorScheme".into(), json!({"dark": scheme_name(true), "light": scheme_name(false)}));
    root.insert("theme".into(), scheme_name(dark).into());
    write_if_changed(path, &(to_json(&settings, 4) + "\n"))
}

fn array_entry<'a>(m: &'a mut Map<String, Value>, key: &str) -> Result<&'a mut Vec<Value>> {
    m.entry(key).or_insert_with(|| Value::Array(vec![])).as_array_mut().ok_or(format!("{key} is not a list"))
}

fn object_entry<'a>(m: &'a mut Map<String, Value>, key: &str) -> Result<&'a mut Map<String, Value>> {
    m.entry(key).or_insert_with(|| Value::Object(Map::new())).as_object_mut().ok_or(format!("{key} is not an object"))
}

fn upsert(items: &mut Vec<Value>, entry: Value) {
    match items.iter_mut().find(|item| item.get("name") == entry.get("name")) {
        Some(item) => *item = entry,
        None => items.push(entry),
    }
}

// --- Helpers ---------------------------------------------------------------

/// '#RRGGBB' -> "r;g;b" for an SGR truecolor sequence.
fn ansi_rgb(hex: &str) -> String {
    let [r, g, b] = rgb(hex);
    format!("{r};{g};{b}")
}

/// `amount` of fg over bg. Rounds half to even, like the Python original.
fn mix(fg: &str, bg: &str, amount: f64) -> String {
    let (f, b) = (rgb(fg), rgb(bg));
    let ch = |i: usize| (f64::from(f[i]) * amount + f64::from(b[i]) * (1.0 - amount)).round_ties_even() as u8;
    format!("#{:02X}{:02X}{:02X}", ch(0), ch(1), ch(2))
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    chars.next().map(|f| f.to_uppercase().chain(chars.flat_map(char::to_lowercase)).collect()).unwrap_or_default()
}

pub fn to_json(v: &Value, indent: usize) -> String {
    let indent = " ".repeat(indent);
    let mut out = Vec::new();
    let fmt = serde_json::ser::PrettyFormatter::with_indent(indent.as_bytes());
    let mut ser = serde_json::Serializer::with_formatter(&mut out, fmt);
    serde::Serialize::serialize(v, &mut ser).expect("JSON values always serialize");
    String::from_utf8(out).expect("serde_json writes UTF-8")
}

/// Text as Python's open(encoding="utf-8-sig") reads it: BOM dropped and
/// newlines normalised to \n, so a CRLF file compares equal to its LF twin.
fn read_text(path: &Path) -> std::io::Result<String> {
    let text = std::fs::read_to_string(path)?;
    let text = text.strip_prefix('\u{FEFF}').unwrap_or(&text);
    Ok(text.replace("\r\n", "\n").replace('\r', "\n"))
}

pub fn write_if_changed(path: &Path, text: &str) -> Result<bool> {
    if read_text(path).is_ok_and(|old| old == text) {
        return Ok(false);
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".m3tmp");
    std::fs::write(&tmp, text).map_err(|e| format!("{}: {e}", path.display()))?;
    // atomic: a terminal never reads half a file
    std::fs::rename(&tmp, path).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

pub fn home() -> PathBuf {
    PathBuf::from(std::env::var_os("USERPROFILE").unwrap_or_default())
}
